# Generated by Django 4.1rc1 on 2022-07-20 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IMS_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendence',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
