# Generated by Django 4.1rc1 on 2022-07-20 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IMS_app', '0002_attendence_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendence',
            name='status',
            field=models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='intern',
            name='task',
            field=models.ManyToManyField(to='IMS_app.task'),
        ),
    ]
