# Generated by Django 4.1rc1 on 2022-07-20 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IMS_app', '0004_rename_name_task_description_remove_intern_task_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supervisor',
            name='email',
            field=models.EmailField(max_length=200, null=True),
        ),
    ]
