# Generated by Django 4.1rc1 on 2022-07-20 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IMS_app', '0007_remove_attendence_name_attendence_intern'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendence',
            name='date_created',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
