# Generated by Django 4.1rc1 on 2022-07-20 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IMS_app', '0008_alter_attendence_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendence',
            name='date_created',
            field=models.DateField(blank=True, null=True),
        ),
    ]
