# Generated by Django 4.1rc1 on 2022-07-20 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IMS_app', '0010_alter_attendence_date_created_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendence',
            old_name='intern',
            new_name='internName',
        ),
    ]
