# Generated by Django 4.1rc1 on 2022-07-20 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IMS_app', '0011_rename_intern_attendence_internname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendence',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='attendence',
            name='internName',
        ),
    ]
