# Generated by Django 4.1rc1 on 2022-07-20 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IMS_app', '0013_attendence_intern'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendence',
            name='TodaysDate',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
