# Generated by Django 4.1rc1 on 2022-07-20 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IMS_app', '0014_attendence_todaysdate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendence',
            old_name='intern',
            new_name='intern_name',
        ),
    ]
