# Generated by Django 4.1rc1 on 2022-07-20 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IMS_app', '0016_alter_attendence_todaysdate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendence',
            old_name='TodaysDate',
            new_name='attendence_date',
        ),
    ]
