# Generated by Django 4.1rc1 on 2022-07-20 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IMS_app', '0017_rename_todaysdate_attendence_attendence_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendence',
            old_name='intern_name',
            new_name='intern_id',
        ),
    ]
