# Generated by Django 4.1rc1 on 2022-07-21 05:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('IMS_app', '0018_rename_intern_name_attendence_intern_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendence',
            name='intern_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='IMS_app.intern'),
        ),
    ]
