# Generated by Django 4.1rc1 on 2022-07-22 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('IMS_app', '0023_remove_intern_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assign_task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
                ('description', models.CharField(max_length=200, null=True)),
                ('date_created', models.DateField(auto_now=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('allot_to', models.ManyToManyField(to='IMS_app.intern')),
                ('alloted_by', models.ManyToManyField(to='IMS_app.supervisor')),
            ],
        ),
        migrations.CreateModel(
            name='Task_for_intern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('intern', models.ManyToManyField(to='IMS_app.intern')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IMS_app.assign_task')),
            ],
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
